server:
  port: 8080
  origin: ${ORIGIN:*}
spring:
  application:
    name: game-commands
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}  
  data:
    mongodb:
        uri: ${MONGO_URI:mongodb://localhost:27017/game-events}
  sleuth:
    sampler:
      percentage: 1.0
microservice:
  exchange: ${EXCHANGE:core-game}
  queue: ${QUEUE:game.commandhandles}
  storeName: ${STORE_NAME:game}
  routingKey: ${ROUTING_KEY:cardgame.#}




