apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-master
  labels:
    {{- include "cardgame-core.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cardgame-core.name" . }}-master
    app.kubernetes.io/instance: {{ .Release.Name }}-master
